name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Enable web
        run: flutter config --enable-web

      - name: Build web release
        run: flutter build web --release --web-renderer auto --tree-shake-icons

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
        env:
          FIREBASE_PROJECT_ID: coinpath789
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Cache bust (optional)
        run: echo "Deployed at $(date -u)"